"""辅助校验显式公式、初值、矩阵与关键积分恒等式；不代替证明或独立阅读。"""
import json
from pathlib import Path
import sympy as S
x,t,a,b,k,c,w,wn=S.symbols('x t a b k c w wn', real=True)
checks=[]
def check(name,expr):
 r=S.simplify(S.expand(expr));checks.append({'name':name,'residual':str(r),'passed':r==0});assert r==0,(name,r)
def ode(name,f,coeff,rhs):check(name,sum(v*S.diff(f,t,j) for j,v in enumerate(coeff))-rhs)
ode('rec01 general',a/k+c*S.exp(k*t),[-k,1],-a)
check('rec02 linear',S.diff(x/2-S.Rational(1,4)+c*S.exp(-2*x),x)-(x-2*(x/2-S.Rational(1,4)+c*S.exp(-2*x))))
# Integral representation U=e^{-x^2/2} I: differentiation integrand and integration by parts.
H=t**S.Rational(-1,2)*S.exp(-t*t/2-S.sqrt(2)*x*t)
check('rec02 U integrand ode',S.diff(S.exp(-x*x/2)*H,x,2)-x*x*S.exp(-x*x/2)*H+2*S.exp(-x*x/2)*S.diff(t*H,t))
ode('rec03 salt',c*(1-S.exp(-2*t)),[2,1],2*c)
z=c-2*c*t*S.exp(-2*t)+c*(2-S.exp(2))*S.exp(-2*t)
ode('rec03 second tank',z,[2,1],2*c*(1-S.exp(-2*t)));check('rec03 second tank initial',z.subs(t,1))
f=(k*k*S.cos(w*t)+k*w*S.sin(w*t))/(k*k+w*w)+c*S.exp(-k*t)
ode('rec04 tide',f,[k,1],k*S.cos(w*t))
y=(c-S.cos(2*x)/2)/x**2;check('rec04 product',x*x*S.diff(y,x)+2*x*y-S.sin(2*x))
for n in range(-4,5):check('rec05 integer power '+str(n),(1+S.sqrt(3)*S.I)**n-2**n*(S.cos(n*S.pi/3)+S.I*S.sin(n*S.pi/3)))
# use exact Rational for negative integer powers (python float could otherwise enter)
for name,f,rhs in [('rec05 cosine',(S.cos(2*t)+S.sin(2*t))/4,S.cos(2*t)),('rec05 sine',(S.sin(2*t)-S.cos(2*t))/4,S.sin(2*t))]:ode(name,f,[2,1],rhs)
for f in [S.cos(w*t),S.sin(w*t)]:ode('rec07 harmonic '+str(f),f,[w*w,0,1],0)
for f in [S.cosh(a*t),S.sinh(a*t)/a]:ode('rec07 hyperbolic '+str(f),f,[-a*a,0,1],0)
for f in [(1+t)*S.exp(-t),t*S.exp(-t),(2+5*t)*S.exp(-t)]:ode('rec08 critical '+str(f),f,[1,2,1],0)
ode('rec09 sine',-S.sin(3*t)/5,[4,0,1],S.sin(3*t));ode('rec09 cos',S.cos(w*t)/(4-w*w),[4,0,1],S.cos(w*t))
ode('rec09 fourth exponential',S.exp(-2*t)/15,[-1,0,0,0,1],S.exp(-2*t));ode('rec09 fourth cosine',S.cos(2*t)/15,[-1,0,0,0,1],S.cos(2*t))
ode('rec10 gain',S.Rational(2,3)*(S.cos(t)+S.sin(t)),[4,3,1],4*S.cos(t))
ode('rec10 polynomial',-t*t-t-3,[-1,0,1],t*t+t+1);ode('rec10 resonance',t*S.sin(2*t)/4,[4,0,1],S.cos(2*t))
ode('rec11 resonance forcing',(t*t/2-t)*S.exp(-t),[2,3,1],t*S.exp(-t))
check('rec11 resonance minimum',S.diff(w**4-S.Rational(63,16)*w*w+4,w).subs(w,3*S.sqrt(14)/8))
for freq,sgn in [((S.sqrt(129)-1)/8,1),((S.sqrt(129)+1)/8,-1)]:check('rec11 phase '+str(sgn),2-freq**2-sgn*freq/4)
ode('rec13 resonance',t*S.sin(wn*t)/(2*wn),[wn*wn,0,1],S.cos(wn*t))
kp=S.symbols('kp',positive=True,integer=True)
check('rec14 coefficient',S.integrate(4*S.cos(kp*t),(t,0,S.pi/2))/S.pi-4*S.sin(kp*S.pi/2)/(kp*S.pi))
ode('rec16 step',1-S.exp(-t/2),[1,2],1);ode('rec16 impulse ordinary',S.exp(-t/2)/2,[1,2],0)
ode('rec16 second impulse ordinary',(1-S.exp(-2*t))/2,[0,2,1],0)
check('rec16 second impulse derivative at zero',S.diff((1-S.exp(-2*t))/2,t).subs(t,0)-1)
ode('rec17 resonant zero initial',(S.sin(t)-t*S.cos(t))/2,[1,0,1],S.sin(t))
f=(S.sin(t)-t*S.cos(t))/2;check('rec17 initial position',f.subs(t,0));check('rec17 initial velocity',S.diff(f,t).subs(t,0))
s=S.symbols('s');check('rec18 inverse ii',-2/s+S.Rational(3,2)/(s-1)+S.Rational(3,2)/(s+1)-(s*s+2)/(s**3-s))
check('rec18 inverse iii',-2/s-2/s**2+2/(s-1)-2/(s*s*(s-1)))
ode('rec18 initial ode',t*t/2-t/2+S.Rational(1,4)+S.Rational(3,4)*S.exp(-2*t),[2,1],t*t)
ode('rec19 input',(S.exp(-t)-S.exp(-3*t))/2,[3,1],S.exp(-t))
ode('rec19 third impulse ordinary',1-S.cos(t),[0,1,0,1],0)
for A in [S.Matrix([[-5,-3],[6,4]]),S.Matrix([[4,3],[-6,-5]])]:
 for lam in [1,-2]:check('rec22 characteristic '+str(A)+str(lam),(A-lam*S.eye(2)).det())
A=S.Matrix([[a,2],[-2,-1]]);N=A-(a-1)*S.eye(2)/2
for v in N*N-(a+5)*(a-3)*S.eye(2)/4:check('rec23 Cayley Hamilton',v)
A=S.Matrix([[1,1],[-4,1]]);E=S.exp(t)*S.Matrix([[S.cos(2*t),S.sin(2*t)/2],[-2*S.sin(2*t),S.cos(2*t)]])
for v in S.diff(E,t)-A*E:check('rec24 matrix ode',v)
for v in E.subs(t,0)-S.eye(2):check('rec24 matrix initial',v)
for v in A*S.Matrix([1,-6])+S.Matrix([5,10]):check('rec24 equilibrium',v)
y=S.symbols('y',positive=True);xx=S.symbols('xx',positive=True)
V=xx-1-S.log(xx)+y-1-S.log(y)
check('rec25 Lyapunov',S.diff(V,xx)*xx*(2-xx-y)+S.diff(V,y)*(xx-1)*y+(xx-1)**2)
result={'checks':checks,'count':len(checks),'all_passed':all(c['passed'] for c in checks),'scope':'仅显式表达式及关键恒等式辅助检查；非完整数学审稿'}
Path(__file__).with_suffix('.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n');print(result['count'],result['all_passed'])
